// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports
  
import { Link, Text, useSitecore, Placeholder, RichText, Image, NextImage, withDatasourceCheck, CdpHelper } from '@sitecore-content-sdk/nextjs';
import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import React from 'react';
import { personalize } from '@sitecore-cloudsdk/personalize/browser';
import { useI18n } from 'next-localization';
import { useRouter } from 'next/router';
import useVisibility from 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/src/hooks/useVisibility';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, EffectCoverflow, Pagination, Navigation } from 'swiper/modules';
import { CountUp } from 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/src/components/NonSitecore/CountUp';
import { DottedAccent } from 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/src/components/NonSitecore/DottedAccent';
import { ParallaxBackgroundImage } from 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/src/components/NonSitecore/ParallaxBackgroundImage';
import NextLink from 'next/link';
import { FacebookIcon, FacebookShareButton, LinkedinIcon, LinkedinShareButton, TwitterIcon, TwitterShareButton } from 'react-share';
import { ParallaxBanner, Parallax } from 'react-scroll-parallax';
import { IconAccent } from 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/src/components/NonSitecore/IconAccent';
import Head from 'next/head';
import client from 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/src/lib/sitecore-client';
import NextjsImage from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/sitecore.config';
    
const importMap = [
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'Placeholder', value: Placeholder },
      { name: 'RichText', value: RichText },
      { name: 'Image', value: Image },
      { name: 'NextImage', value: NextImage },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useEffect', value: useEffect },
      { name: 'useCallback', value: useCallback },
      { name: 'useMemo', value: useMemo },
      { name: 'useRef', value: useRef },
      { name: 'default', value: React },
    ]
  },
  {
    module: '@sitecore-cloudsdk/personalize/browser',
    exports: [
      { name: 'personalize', value: personalize },
    ]
  },
  {
    module: 'next-localization',
    exports: [
      { name: 'useI18n', value: useI18n },
    ]
  },
  {
    module: 'next/router',
    exports: [
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/src/hooks/useVisibility',
    exports: [
      { name: 'default', value: useVisibility },
    ]
  },
  {
    module: 'swiper/react',
    exports: [
      { name: 'Swiper', value: Swiper },
      { name: 'SwiperSlide', value: SwiperSlide },
    ]
  },
  {
    module: 'swiper/modules',
    exports: [
      { name: 'Autoplay', value: Autoplay },
      { name: 'EffectCoverflow', value: EffectCoverflow },
      { name: 'Pagination', value: Pagination },
      { name: 'Navigation', value: Navigation },
    ]
  },
  {
    module: 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/src/components/NonSitecore/CountUp',
    exports: [
      { name: 'CountUp', value: CountUp },
    ]
  },
  {
    module: 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/src/components/NonSitecore/DottedAccent',
    exports: [
      { name: 'DottedAccent', value: DottedAccent },
    ]
  },
  {
    module: 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/src/components/NonSitecore/ParallaxBackgroundImage',
    exports: [
      { name: 'ParallaxBackgroundImage', value: ParallaxBackgroundImage },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: NextLink },
    ]
  },
  {
    module: 'react-share',
    exports: [
      { name: 'FacebookIcon', value: FacebookIcon },
      { name: 'FacebookShareButton', value: FacebookShareButton },
      { name: 'LinkedinIcon', value: LinkedinIcon },
      { name: 'LinkedinShareButton', value: LinkedinShareButton },
      { name: 'TwitterIcon', value: TwitterIcon },
      { name: 'TwitterShareButton', value: TwitterShareButton },
    ]
  },
  {
    module: 'react-scroll-parallax',
    exports: [
      { name: 'ParallaxBanner', value: ParallaxBanner },
      { name: 'Parallax', value: Parallax },
    ]
  },
  {
    module: 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/src/components/NonSitecore/IconAccent',
    exports: [
      { name: 'IconAccent', value: IconAccent },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: NextjsImage },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'C:/Repo/Stream-Demo-Powerful/src/sxastarter/sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
